#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'

require 'ap'
require 'active_record'
require 'devise'
require 'devise/orm/active_record'

root_path = File.expand_path("../..", __FILE__)
$LOAD_PATH.unshift(root_path) unless $LOAD_PATH.include?(root_path)

ActiveSupport::Dependencies.autoload_paths << 'app/models'
ActiveSupport::Dependencies.autoload_paths << 'lib'

# Load database config
env = ENV['RAILS_ENV'] || 'development'
database_config = YAML::load(File.open(File.join(root_path, 'config', 'database.yml')))[env]
ActiveRecord::Base.establish_connection(database_config)

# TODO do sth with the db
ap User.all
